server:
  port : 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passmanager
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  application:
    name: PASSWORD-MANAGEMENT-SERVICE

jwt:
  cookieExpiry: 1200
